---
title: "Used Car Price Prediction"
output: html_notebook
---

```{r}
if (!require("psych")) {install.packages("psych", dependencies = TRUE)}
library(psych)
if (!require("corrplot")) {install.packages("psych", dependencies = TRUE)}
library(corrplot)
usedcar <- read.csv("C:/Users/buiha/Desktop/LATROBE DOC/PREDICTIVES ANALYTICS/ASSIGNMENT/1/used_car.csv")
View(usedcar)

# Clean up dirty data in column "front_legroom" and convert back to numerical
usedcar$front_legroom[usedcar$front_legroom == "#FIELD!"] <- NA
usedcar$front_legroom <- as.numeric(as.character(usedcar$front_legroom))

# Investigate dataset
names(usedcar)
str(usedcar)
summary(usedcar)
sapply(usedcar, class)

```


```{r 1.c}
#PART B: DATA EXPLORATION AND CLEANING
#Task 1.c.
# Create a copy of the usedcar dataframe
updated_usedcar <- usedcar

# Transform nominal categorical columns to numerical
# Column: body_type
updated_usedcar$sedan_bodytype <- as.numeric(updated_usedcar$body_type == "Sedan")
updated_usedcar$suv_bodytype <- as.numeric(updated_usedcar$body_type == "SUV / Crossover")
updated_usedcar$hatchback_bodytype <- as.numeric(updated_usedcar$body_type == "Hatchback")
# Column: fuel_type
updated_usedcar$gasoline_fueltype <- as.numeric(updated_usedcar$fuel_type == "Gasoline")
updated_usedcar$hybrid_fueltype <- as.numeric(updated_usedcar$fuel_type == "Hybrid")
updated_usedcar$diesel_fueltype <- as.numeric(updated_usedcar$fuel_type == "Diesel")
# Column: make_name
updated_usedcar$bmw_makename <- as.numeric(updated_usedcar$make_name == "BMW")
updated_usedcar$ford_makename <- as.numeric(updated_usedcar$make_name == "Ford")
updated_usedcar$audi_makename <- as.numeric(updated_usedcar$make_name == "Audi")
updated_usedcar$merc_makename <- as.numeric(updated_usedcar$make_name == "Mercedes-Benz")
updated_usedcar$volk_makename <- as.numeric(updated_usedcar$make_name == "Volkswagen")
updated_usedcar$toyota_makename <- as.numeric(updated_usedcar$make_name == "Toyota")
# Column: salvage
updated_usedcar$num_salvage <- factor(updated_usedcar$salvage, levels=c(FALSE,TRUE), labels=c(0,1))
updated_usedcar$num_salvage <- as.numeric(as.character(updated_usedcar$num_salvage))
# Column: transmission
updated_usedcar$auto_transmission <- as.numeric(updated_usedcar$transmission == "Automatic")
updated_usedcar$continuous_transmission <- as.numeric(updated_usedcar$transmission == "Continuously Variable Transmission")
updated_usedcar$manual_transmission <- as.numeric(updated_usedcar$transmission == "Manual")
updated_usedcar$dual_transmission <- as.numeric(updated_usedcar$transmission == "Dual Clutch")
# Column: wheel_system
updated_usedcar$all_wheelsystem <- as.numeric(updated_usedcar$wheel_system == "All-Wheel Drive")
updated_usedcar$front_wheelsystem <- as.numeric(updated_usedcar$wheel_system == "Front-Wheel Drive")
updated_usedcar$rear_wheelsystem <- as.numeric(updated_usedcar$wheel_system == "Rear-Wheel Drive")
updated_usedcar$four_wheelsystem <- as.numeric(updated_usedcar$wheel_system == "Four-Wheel Drive")

# Transform ordinal categorical columns to numerical
# Column: condition
updated_usedcar$num_condition <- factor(updated_usedcar$condition, levels=c("Fair","Good","Excellent"), labels=c(0,1,2))
updated_usedcar$num_condition <- as.numeric(as.character(updated_usedcar$num_condition))
# Column: engine_cylinders
updated_usedcar$num_enginecylinders <- factor(updated_usedcar$engine_cylinders, levels=c("3 Cylinders","4 Cylinders", "5 Cylinders","6 Cylinders", "8 Cylinders","12 Cylinders"), labels=c(0,1,2,3,4,5))
updated_usedcar$num_enginecylinders <- as.numeric(as.character(updated_usedcar$num_enginecylinders))
# Column: maximum_seating
updated_usedcar$num_maximumseating <- factor(updated_usedcar$maximum_seating, levels=c("4 seats","5 seats", "6 seats", "7 seats", "8 seats"), labels=c(0,1,2,3,4))
updated_usedcar$num_maximumseating <- as.numeric(as.character(updated_usedcar$num_maximumseating))

# Remove original categorical columns
updated_usedcar = subset(updated_usedcar, select = -c(body_type, fuel_type, make_name, salvage, transmission, wheel_system, condition, engine_cylinders, maximum_seating))

print(updated_usedcar)
```


```{r 2.}
#Task 2:
#a. (i).Summary statistics for numerical columns
numerical_cols <- sapply(usedcar, is.numeric)
numerical_usedcar <- usedcar[, numerical_cols]
describe(numerical_usedcar, fast=TRUE)
#(ii). Count for categorical columns
categorical_counts <- sapply(usedcar[, sapply(usedcar, is.character)], table)
print(categorical_counts)
#b. Visualize box plots for checking extreme values
par(mfrow = c(3, 3))  
for (col in names(numerical_usedcar)) {boxplot(usedcar[[col]], main = col, xlab = col, ylab = "Value")}
```


```{r 3.}
#Task 3:
#a & b.
# Continuous variables
continuous_vars <- c("price", "back_legroom", "city_fuel_economy", "front_legroom", 
                     "fuel_tank_volume", "height", "highway_fuel_economy", "horsepower",
                     "length", "mileage", "wheelbase", "width", "daysonmarket")
library(purrr)
library(tidyr)
library(ggplot2)
library(dplyr)
#Create histograms for continuous variables
suppressWarnings(updated_usedcar %>% select(all_of(continuous_vars)) %>%  gather() %>% ggplot(aes(value)) + facet_wrap(~ key, scales = "free") +geom_histogram())

#c. Values that seem extreme
# Log Transformation for "mileage", "city_fuel_economy" and "daysonmarket" (right-skewed variables)
cols <- c("mileage", "city_fuel_economy", "daysonmarket")
updated_usedcar[cols] <- log(updated_usedcar[cols] + 0.00001) #Adding a small constant(0.00001), to prevent the calculation of the logarithm of zero.
# Check those variables after transformation
par(mfrow = c(2, 2))  
for (col in cols) {density_before <- density(usedcar[[col]], na.rm = TRUE)
    plot(density_before, main = paste("Before:", col), xlab = col, ylab = "Density")
    density_after <- density(updated_usedcar[[col]], na.rm = TRUE)
    plot(density_after, main = paste("After:", col), xlab = col, ylab = "Density")}
```
```{r 4.}
#Task 4
#a.Check for missing values in each variable
missing_values <- colSums(is.na(updated_usedcar))
columns_have_missingvalues <- names(missing_values[missing_values > 0])
print(missing_values)
print(columns_have_missingvalues)

#c. 3 methods of handling missning values
#Method 1: Replace missing values with 0
usedcar_replacebyzero <- updated_usedcar
usedcar_replacebyzero[is.na(usedcar_replacebyzero)] <- 0

# Method 2: Delete records with missing values
usedcar_deletemissing <- na.omit(updated_usedcar)

# Method 3:  Replace missing values with mean of the column
usedcar_final <- updated_usedcar
for (col in continuous_vars) { 
  mean_val <- mean(updated_usedcar[[col]], na.rm = TRUE) 
  usedcar_final[[col]][is.na(usedcar_final[[col]])] <- mean_val}


par(mfrow = c(2, 2))
# Plot Method 1: Replace with 0
plot(density(updated_usedcar$front_legroom, na.rm = TRUE), col = "blue", main = "Method 1")
lines(density(usedcar_replacebyzero$front_legroom, na.rm = TRUE), col = "red")
# Plot Method 2: Delete Records
plot(density(updated_usedcar$front_legroom, na.rm = TRUE), col = "blue", main = "Method 2")
lines(density(usedcar_deletemissing$front_legroom, na.rm = TRUE), col = "orange")
# Plot Method 3: Replace with Mean
plot(density(updated_usedcar$front_legroom, na.rm = TRUE), col = "blue", main = "Method 3")
lines(density(usedcar_final$front_legroom, na.rm = TRUE), col = "green")

# There are over 20,000 rows in the data in total with only under 100 rows with missing data, 
# therefore there is minimal difference between the 3 methods of handling missing data

# Compare mean of dataset to 
original_mean <- mean(updated_usedcar$front_legroom, na.rm = TRUE)
print(paste("Usedcar original mean is", original_mean))

mean_1 <- mean(usedcar_replacebyzero$front_legroom, na.rm = TRUE)
print(paste("Mean value of method 1 is", mean_1))

mean_2 <- mean(usedcar_deletemissing$front_legroom, na.rm = TRUE)
print(paste("Mean value of method 2 is", mean_2))

mean_3 <- mean(usedcar_final$front_legroom, na.rm = TRUE)
print(paste("Mean value of method 3 is", mean_3))


#Method 3 is the most suitable method to handle missing value for this dataset. 

```




```{r 5.}
#Task 5
if (!requireNamespace("corrplot", quietly = TRUE)) {install.packages("corrplot", dependencies = TRUE)}
library(corrplot)
if (!require("GGally")) {install.packages("GGally", dependencies = TRUE)}
library(GGally)
if (!require("caret")) {install.packages("caret", dependencies = TRUE)}
library(caret)

#a. Evaluate correlations of variables.
# We will use usedcar_final from method 3 for further analysis
target <- usedcar_final$price
# Remove the target variable and create a new dataframe with only the attributes
usedcar_attributes <- subset(usedcar_final, select = -c(price))
# Analyze the correlation of attributes
ggcorr(usedcar_attributes, label = TRUE,
       label_size = 1.2, 
       hjust = 1, vjust = 0.1, size = 2, layout.exp = 1)

#b. Dimension Reduction
# Get the column names that are highly correlated
M <- data.matrix(usedcar_attributes)
corrM <- cor(M)
highlyCorrM <- findCorrelation(corrM, cutoff=0.9)
names(usedcar_attributes)[highlyCorrM]

# Evaluate correlation of the dimension reduced dataset
usedcar_selected <- subset(usedcar_attributes, select = -c(city_fuel_economy, front_wheelsystem, height, suv_bodytype, engine_displacement))
suppressWarnings({ggcorr(usedcar_selected,label = TRUE, label_size = 1.2, label_position = "top", 
       ggtheme = ggplot2::theme_minimal(), 
       hjust = 1, vjust = 0.1, size = 2, layout.exp = 1)})
#Merge the target variable back to the dataset
usedcar_selected$price <- target

#c. Compare distribution of selected variables with target variable "price" by scatter plot matrix
if (!requireNamespace("GGally", quietly = TRUE)) {install.packages("GGally", dependencies = TRUE)}
library(GGally)
columns <- c("price", "city_fuel_economy", "front_wheelsystem", "height", "suv_bodytype", "engine_displacement")
ggpairs(data = usedcar_final, columns = columns,
        lower = list(continuous = "smooth"),
        title = "Scatterplot Matrix of Used Car Features", progress = FALSE)

```
```{r}
#PART C: BUILDING PREDICTIVE MODELS
#Task 1.a.
#Data Partition
smp_size <- floor(2/3 * nrow(usedcar_selected))
set.seed(1)
usedcar_selected <- usedcar_selected[sample(nrow(usedcar_selected)), ]
usedcar.train <- usedcar_selected[1:smp_size, ]
usedcar.test <- usedcar_selected[(smp_size+1):nrow(usedcar_selected), ]
print(usedcar.train)
print(usedcar.test)
#Build the predictive model
formula = price ~.
model <- lm(formula = formula, data = usedcar.train)
summary(model)$coefficients
regression_equation <- as.formula( paste0("y ~ ", round(coefficients(model)[1], 2), " + ", 
         paste(sprintf("%.2f * `%s`", coefficients(model)[-1], 
                       names(coefficients(model)[-1])), 
               collapse = " + ")))
print(regression_equation)

usedcar.test$predicted.price <- predict(model, usedcar.test)
# Evaluation of model
r_squared <- summary(model)$r.squared
print(paste("R Squared: ", r_squared))

error <- usedcar.test$price - usedcar.test$predicted.price
rmse <- sqrt(mean(error^2))
print(paste("Root Mean Square Error: ", rmse))

```

```{r}
#Task 1.b & c
#Model 1
formula1 = price ~  mileage + year + horsepower + bmw_makename + ford_makename+ audi_makename+ merc_makename + volk_makename + auto_transmission + continuous_transmission + manual_transmission + num_condition   
model1 <- lm(formula = formula1, data = usedcar.train)
summary(model1)$coefficients
model1_regression <- as.formula(paste0("price ~ ", round(coefficients(model1)[1], 2), " + ", 
         paste(sprintf("%.2f * `%s`", coefficients(model1)[-1], names(coefficients(model1)[-1])), collapse = " + ")))
print(model1_regression)

usedcar.test$predicted.price <- predict(model1, usedcar.test)
# Evaluation of model1
r_squared <- summary(model1)$r.squared
print(paste("R Squared: ", r_squared))
error <- usedcar.test$price - usedcar.test$predicted.price
rmse <- sqrt(mean(error^2))
print(paste("Root Mean Square Error: ", rmse))

#Model 2
formula2 = price ~  merc_makename + bmw_makename + audi_makename + four_wheelsystem + year + mileage + sedan_bodytype + gasoline_fueltype + hybrid_fueltype + ford_makename
model2 <- lm(formula = formula2, data = usedcar.train)
summary(model2)$coefficients
model2_regression <- as.formula(
  paste0("price ~ ", round(coefficients(model2)[1], 2), " + ", paste(sprintf("%.2f * `%s`", coefficients(model2)[-1], 
        names(coefficients(model2)[-1])), collapse = " + ")))
print(model2_regression)
usedcar.test$predicted.price <- predict(model2, usedcar.test)

# Evaluation of model 2
r_squared <- summary(model2)$r.squared
print(paste("R Squared: ", r_squared))
error <- usedcar.test$price - usedcar.test$predicted.price
rmse <- sqrt(mean(error^2))
print(paste("Root Mean Square Error: ", rmse))
```

```{r}
#Task 2.a. Build decision tree 

library(GGally)
if (!requireNamespace("rpart", quietly = TRUE)) {install.packages("rpart", dependencies = TRUE)}
library(rpart)
if (!requireNamespace("rpart.plot", quietly = TRUE)) {install.packages("rpart.plot", dependencies = TRUE)}
library(rpart.plot)
#Sample the dataset
set.seed(2)
usedcar_tree.selected <- usedcar_selected[sample(nrow(usedcar_selected)), ]
sample(5)
View(usedcar_tree.selected)
usedcar_tree.train <- usedcar_tree.selected[1:smp_size, ]  
usedcar_tree.test <- usedcar_tree.selected[(smp_size+1):nrow(usedcar_tree.selected), ] 

formula = price ~.
dtree <- rpart(formula, data=usedcar_tree.train, method="anova")
dtree$variable.importance
rpart.plot(dtree, type = 4, fallen.leaves = FALSE)
print(dtree)

# Evaluate model
usedcar_tree.test$predicted_price <- predict(dtree, usedcar_tree.test)
error_new <- usedcar_tree.test$price - usedcar_tree.test$predicted_price
rmse_new <- sqrt(mean(error_new^2))
print(paste("Original Root Mean Square Error: ", rmse_new))

```

```{r}
#Task 2.b.
#Evaluate decision tree model
printcp(dtree)
cp_best = dtree$cptable[which.min(dtree$cptable[,"xerror"]),"CP"]
cat("Best Complexity Parameter:", cp_best, "\n")

#Prune the tree with best cp value (complexity parameter)
pruned_dtree1 <- prune(dtree, cp = 0.010000)
rpart.plot(pruned_dtree1, type = 4, fallen.leaves = FALSE)

pruned_dtree2 <- prune(dtree, cp = 0.011867) 
rpart.plot(pruned_dtree2, type = 4, fallen.leaves = FALSE) 

pruned_dtree3 <- prune(dtree, cp =  0.012433) 
rpart.plot(pruned_dtree3, type = 4, fallen.leaves = FALSE)

usedcar_tree.test$predicted_price1 <- predict(pruned_dtree1, usedcar_tree.test)
error_new1 <- usedcar_tree.test$price - usedcar_tree.test$predicted_price1
rmse_new1 <- sqrt(mean(error_new1^2))

usedcar_tree.test$predicted_price2 <- predict(pruned_dtree2, usedcar_tree.test)
error_new2 <- usedcar_tree.test$price - usedcar_tree.test$predicted_price2
rmse_new2 <- sqrt(mean(error_new2^2))

usedcar_tree.test$predicted_price3 <- predict(pruned_dtree3, usedcar_tree.test)
error_new3 <- usedcar_tree.test$price - usedcar_tree.test$predicted_price3
rmse_new3 <- sqrt(mean(error_new3^2))

print(paste("RMSE of Tree Model 1:", rmse_new1))
print(paste("RMSE of Tree Model 2:", rmse_new2))
print(paste("RMSE of Tree Model 3:", rmse_new3))
```


